<div id="page" class="col">
	 	
	<div class="chemindefer">Vous etes ici : <a href="<?php print $this->baseUrl();?>/index.html">Accueil</a> &gt; <a href="<?php print $this->baseUrl();?>/agenda/">Agenda</a> <?php 
		$titrepage = "Agenda";
		foreach ($this->categories as $categorie){
			$value 	= strtolower($categorie);
			if($value==strtolower($this->type)){
				$titrepage = $categorie;
				print ' &gt; <a href="'.$this->baseUrl().'/agenda/'.$this->type.'/">'.$categorie.'</a>';
			}
		}
		
		?></div>

	<h1><?php print $titrepage;?></h1>
	
	<div style="width:98%;" id="content">
		<div style="float:right;">
			<select onchange="document.location.href='<?php print $this->baseUrl();?>/agenda/'+this.value">
				<option value="">Selectionnez une categorie</option>
				<?php
				foreach ($this->categories as $categorie){
					$name 	= $categorie;
					$value 	= strtolower($categorie);
					if($value==strtolower($this->type)){
						print '<option value="'.$value.'/" selected="selected">'.$name.'</option>';
					}else{
						print '<option value="'.$value.'/">'.$name.'</option>';
					}
				}
				?>
			</select>
		</div>
		<div class="clearer"></div>
		<div>
			<div class="special">
				<?php
				 	foreach($this->evenements as $event){
				 ?>
					<ul>
						<li>
							<a title="<?php print $event->agenda_titre;?>" href="<?php print $this->baseUrl().$event->url;?>">
								<?php if ($event->agenda_thumb!=""){ ?>
								<img class="vignette" src="<?php print $this->baseUrl().'/'.$event->agenda_thumb;?>" />
								<?php }else{ ?>
								<img class="vignette" src="<?php print $this->baseUrl();?>/skins/images/logo.png" />
								<?php } ?>
							</a>
							<div class="dateevent">
								<?php print $event->agenda_debut;?>
							</div>
							<div>
								<h3 class="normal">
									<a title="<?php print $event->agenda_titre;?>"href="<?php print $this->baseUrl().$event->url;?>"><?php print $event->agenda_titre;?></a>
								</h3>
								<p><?php print$event->agenda_chapeau;?> <span class="typeevent"><?php print $event->agenda_type;?></span></p>	
							</div>
						</li>
					</ul>
				<?php
					}
				?>		
			</div>
			<div id="pagination">
				<?php print $this->pagination;?>
			</div>
		</div>
		
	</div>
</div>