<?php 

	$writer = new XMLWriter();
	$writer->openMemory();
	$writer->startDocument('1.0');
	
	$writer->startElement('root');
		
	foreach($this->videos as $video){
		$writer->startElement('item');
			$writer->writeElement('date', $video['date']);
			$writer->writeElement('titre', $video['titre']);
			$writer->writeElement('file', $video['file']);
	 	$writer->endElement(); // Close item
	}
	 	
	$writer->endElement(); // Close RSS
	$writer->endDocument();
	echo $writer->flush();
	
